defaults:
  - data: part-of-speech-intrasyllabic-olive
  - model: albert-olive-cormorant
  - training: frequent_logs
  - _self_

hydra:
  run:
    dir: ${oc.env:CAI_TEMP_PATH}/pos-tagger/albert-olive-cormorant/${now:%Y-%m-%d}/${now:%H-%M-%S}